apiVersion: v1
kind: Service
metadata:
  name: caller-service2
  labels:
    app: caller-service2
spec:
  ports:
  - port: 8090
    name: http
  selector:
    app: caller-service2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: caller-service-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: caller-service2
        version: v1
    spec:
      containers:
      - name: caller-service2
        image: piomin/caller-service:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090
---

###########################################################################
# (gateway)
##########################################################################
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: caller-service2-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: caller-service2
spec:
  hosts:
  - "*"
  gateways:
  - caller-service2-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: caller-service2
        port:
          number: 8090